name: Tox test on PR

on:
  pull_request:
    branches:
      - stable/2024.1
  workflow_dispatch:

jobs:
  tox:
    name: Run tox tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install tox
        run: pip install tox

      - name: Run flake8 (pep8)
        run: tox -e pep8

      - name: Run unit tests (py310)
        run: tox -e py310
